CREATE TABLE KAKAO(
 	NAME VARCHAR2(20) NOT NULL,
  	EMAIL VARCHAR2(20) NOT NULL,
  	PRICE NUMBER(20) NOT NULL,
  	PHONE VARCHAR2(20),
  	ADDRESS VARCHAR2(50)
);

INSERT INTO KAKAO VALUES('A001','kakao@naver.com',14000,'12341234','서울특별시 금천구 시흥대로');

SELECT NAME ,EMAIL ,PHONE ,ADDRESS ,PRICE 
	FROM KAKAO k ;