CREATE TABLE FILE_BOARD(
	SEQ NUMBER PRIMARY KEY,
	ID VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(50) NOT NULL,
	CONTENT VARCHAR2(4000),
	REFER NUMBER NOT NULL,
	STEP NUMBER NOT NULL,
	"DEPTH" NUMBER NOT NULL,
	READCOUNT NUMBER NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL
);
CREATE TABLE FILE_PHOTO(
	SEQ NUMBER PRIMARY KEY,
	B_SEQ NUMBER NOT NULL,
	IMG_UUID VARCHAR2(200) NOT NULL,
    IMG_ORI VARCHAR2(300),
	IMG_URL VARCHAR2(500)
);
CREATE SEQUENCE FILE_BOARD_SEQ INCREMENT BY 1;
CREATE SEQUENCE FILE_PHOTO_SEQ INCREMENT BY 1;

SELECT * FROM FILE_BOARD;
SELECT * FROM FILE_PHOTO;

DROP TABLE FILE_BOARD;
DROP TABLE FILE_PHOTO;
DROP SEQUENCE FILE_BOARD_SEQ;
DROP SEQUENCE FILE_PHOTO_SEQ;

<insert id="writeBoard" parameterType="com.min.edu.vo.BoardVO">
	<selectKey keyProperty="seq" resultType="int" order="BEFORE">
		SELECT FILE_BOARD_SEQ.NEXTVAL AS SEQ FROM DUAL
	</selectKey>
	INSERT INTO FILE_BOARD
	(SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, DELFLAG, REGDATE)
	VALUES(#{seq}, 'USER01', '#TEST TITLE',
	'TEST CONTENT', (SELECT NVL(MAX(REFER),0)+1 FROM FILE_BOARD), 0,
	0, 0, 'N',
	SYSDATE)
</insert>